management:
  security:
    enabled: false
---
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  profiles: prod
---
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    platform: h2
  profiles: test